name: ci

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    node: [ 8, 9, 10, 11, 12, 13, 14, 15 ]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Node ${{ matrix.node }}
    uses: actions/setup-node@v1
    with:
     node-version: ${{ matrix.node }}
  - run: npm install
  - run: npm run lint
  - run: npm run test:coverage
